title: 一页障目
email: programmerxiao@gmail.com
description: 移动互联网：更多信息，更少信息量。
url: "https://xrefft.github.io"
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
markdown: kramdown
highlighter: rouge
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
  - CODE_OF_CONDUCT.md
  - LICENSE.txt
  - .build.sh.swp
